### ISSUE TITLE
Sample Dataset to test with

### ISSUE THREAD

**Issue by MuSamiNaf** [aqibsaeed/Sensor-Transformer#1]
Hello
Thank you for yout great work developing this code.

I would like to know if there are any ready samples converted to npy file to test the code with.

Thank you

**Comment by aqibsaeed** [comment]
Check this post to prepare the dataset: http://aqibsaeed.github.io/2016-11-04-human-activity-recognition-cnn/

**Comment by MuSamiNaf** [comment]
@aqibsaeed 
Thank you for your super quick reply.

Based on what is written here:

> TF-Data objects, see data.load_data function.
> Instances must be of shape x = (batch, signal_length, num_channels)
> y = (batch, num_classes)


Both the X and Y datasets for training and testing should match the array shapes mentioned above.
Will I get the same outputs from the reference link above? If not, are there any ready npy files at your disposal?

Thank you for your time.

**Comment by aqibsaeed** [comment]
> Both the X and Y datasets for training and testing should match the array shapes mentioned above.

Yes!

> Will I get the same outputs from the reference link above? 

Yes! the data preparation in tutorial generate training and test sets of same shapes.

**Comment by MuSamiNaf** [comment]
Alright. Thank you!
