### ISSUE TITLE
Low Accuracy and Signal/Segment Parameters

### ISSUE THREAD

**Issue by MuSamiNaf** [aqibsaeed/Sensor-Transformer#2]
Hello Aqib

I ran the code the has previously linked to into the issue #1 

After running the code, the generated training/testing  X dataset is 4 dimensions (17111, 1, 90, 3) and (7292, 90, 3) respectively.

I am not aware if what I have done is correct, but I removed the "height" dimension from this line, so the sensorTranformer can to match the input requirments.

> reshaped_segments = segments.reshape(len(segments), 1,90, 3)

to become

> reshaped_segments = segments.reshape(len(segments) ,90, 3)

Regarding signal-length and segment-size, I am not aware of the values that shall be used. I know that the segment-size shall be less than or equal to 90 and as a divisor, the remainder shall be 0. What about the signal-length.

I expirmennt with random values for signal-length and segment-size, 90 and 10 respectively for 50 epochs uwsing GELU activation, however, the resultant accuracy is 0.0957, which is very bad. RELU was much better at around 0.45. What was a bit strange for me is that Swich was around 0.0974, which is as bad as GELU. This is leaving me scratching my head in confusion.

What am I doing wrong here?
Thank you in advance

**Comment by aqibsaeed** [comment]
Your comment regarding shape is correct.
Make sure your data is normalized and you are following other best practices.
